docs/api/index.md, src/verbs/expr/rolling.js, test/expression/parse-test.js
Change the `rolling` helper to be *insensitive* to peer values (ties) by default. This is a breaking change, but seems likely to bring the API more in line with user expectations: the most common peer-sensitive window operations are rolling aggregates (like cumulative sums or windowed counts) where people are unlikely to know in advance about window frame adjustments to include all peer values.
=> Change default peer handling for rolling.

src/table/column-table.js, src/table/table.js, src/util/row-object-builder.js, test/table/column-table-test.js
Adds default iterator support to Arquero tables, producing output row objects.
Close #7
=> Add row object iterator support.

src/op/window-functions.js
Using ntile op results in "cume_dist is not a function" error. It was calling the object instead of its create method.
=> fix: Call create method on cume_dist

src/verbs/join.js, test/verbs/join-test.js
- Update `join()` to drop redundant columns when performing a natural join (that is, when neither a join predicate / keys nor specific output columns are provided).
Close #25.
=> Support natural join.

docs/api/table.md, src/format/to-csv.js, src/format/to-html.js, src/format/to-json.js, src/format/to-markdown.js, src/format/util.js, src/table/bit-set.js, src/table/column-table.js, src/table/table.js, test/format/html-test.js
- Add `null` option to `toHTML` to specialize formatting of null and undefined values.
- Add `offset` option for output formats.
- Add `limit` and `offset` arguments to table `scan` method.
=> Update format and export options.

docs/api/verbs.md, src/query/query-builder.js, src/query/verb.js, src/table/table.js, src/verbs/derive.js, src/verbs/expr/selection.js, src/verbs/index.js, src/verbs/relocate.js, test/query/query-builder-test.js, test/query/query-test.js, test/query/verb-test.js, test/query/verb-to-ast-test.js, test/verbs/derive-test.js, test/verbs/relocate-test.js
* Add `relocate` verb for repositioning and renaming columns.
* Add `derive` verb *before* and *after* options to position new derived columns.
Close #35
=> Add relocate verb, add derive before/after options.

docs/api/index.md, docs/api/op.md, docs/api/verbs.md, src/format/from-arrow.js, test/format/arrow-test.js
- Add `List` and `Struct` type support to `fromArrow()`. Extracts nested values to arrays and objects, respectively.
=> Support nested Arrow types List and Struct.

src/op/aggregate-functions.js, src/util/to-string.js, test/verbs/rollup-test.js
- Consistently handle empty/null input to non-count aggregates, return `undefined`.
- Handle `undefined` input to `toString()`.
Fix #46.
=> Fix empty / null aggregates.

package.json, tsconfig.json, yarn.lock
Opening this PR to start a conversation about supporting TypeScript. This project is close to supporting TypeScript since types can be generated from JSDocs. This PR shows how to generate types for the project and will work as long as the JSDocs are maintained for the public API.
My team and I have been using a local copy of arquero with types generated from the well maintained JSDocs for about two weeks now without any problems. The types align very well with the codebase thanks to the accurate JSDocs. There are few exceptions to this. For example, the JSDocs for `table.filter` states that it expects a `Function` as a param but I believe it actually accepts `Function|string` since `filter` supports table expressions. I am happy to submit PRs for JSDoc updates whenever we find a mismatch …
=> chore: Add typescript types to build output.

src/format/from-arrow.js, src/format/from-csv.js, src/format/from-json.js, src/format/to-csv.js, src/format/to-html.js, src/format/to-json.js, src/format/to-markdown.js, src/op/aggregate-functions.js, src/op/register.js, src/op/window-functions.js, src/query/query-builder.js, src/query/query.js, src/table/column-table.js, src/table/table.js, src/verbs/expr/bin.js, src/verbs/expr/desc.js, src/verbs/expr/field.js, src/verbs/expr/rolling.js, src/verbs/expr/wrap.js, src/verbs/index.js
- Fix JSDoc types to use `object`, not `Object`.
=> Fix JSDoc types to use object, not Object.

src/op/aggregate-functions.js, src/util/distinct-map.js, src/util/entries.js, src/util/is-date.js, src/util/is-regexp.js, src/util/object-to-string.js
- Fix `distinct`, `unique`, and `mode` aggregates to group dates with the same timestamp.
- Fix `entries` utility to return empty array for null input.
- Update `isDate` and `isRegExp` utilities to be more performant.
=> Fix date handling in aggregate functions.

docs/api/verbs.md, src/engine/pivot.js, src/engine/spread.js, src/table/transformable.js, test/query/query-test.js, test/verbs/pivot-test.js, test/verbs/spread-test.js
- Add `drop` option to `spread()` verb to drop input columns, set default to true.
- Revise `spread()` to use `undefined` for missing values.
- Revise `spread()` to use `_` separator between column name and index number in auto-generated names.
- Revise `spread()` to use the length of the `as` option as an implicit limit when `limit` is unspecified.
=> Revise spread verb.

docs/api/table.md, src/format/from-arrow.js, src/format/from-csv.js, src/format/from-json.js, src/format/to-csv.js, src/format/to-html.js, src/format/to-json.js, src/format/to-markdown.js, src/format/util.js, src/format/value.js, src/table/bit-set.js, src/table/column-table.js, src/table/table.js, src/table/transformable.js
- Update JSDoc comments and improve generated TypeScript typings.
- Update [Table](https://uwdata.github.io/arquero/api/table) API docs.
- Fix table iterator filter check bug.
Fix #72.
=> Update JSDoc typings.

src/expression/parse.js, test/expression/parse-test.js
- Update expression parser to support immediately-evaluable expressions for column references.
Fix #74.
=> Allow expression-valued column references.

docs/api/index.md, package.json, perf/csv-perf.js, src/engine/impute.js, src/engine/join.js, src/engine/reduce/field-reducer.js, src/engine/window/window-state.js, src/engine/window/window.js, src/format/from-arrow.js, src/format/from-csv.js, src/util/identity.js, src/util/is-iso-date-string.js, src/util/parse-dsv.js, src/util/parse-iso-date.js, src/util/parse-values.js, src/util/row-object-builder.js, src/util/unroll.js, src/util/unroll2.js, src/verbs/index.js, test/format/csv-test.js
- Update `fromCSV()` parsing to ensure consistent types across column values.
- Add `autoMax` option to `fromCSV()` to control how many initial rows are used for type inference.
- Update `table()` constructor to accept `Map` objects and `[[key, value], ...]` entry arrays as input.
- Add internal performance benchmark scripts.
- Refactor internal loop unrolling utility.
=> Revise CSV auto type inference.

src/table/column.js
This exposes a [Symbol.iterator] method on Column simply by passing through to the underlying data. This means that you can iterate over column values slightly more succinctly (no `.data` required), for example:
```js
for (const value of table.column("foo")) {
console.log(value);
}
```
Or to make a copy of a column:
```js
const foo = Array.from(table.column("foo"));
```
=> Make Column iterable.

docs/api/index.md, docs/api/verbs.md, src/verbs/expr/frac.js, src/verbs/index.js, test/verbs/sample-test.js
- Add `frac()` helper function to generate an expression for per-group row counts. Useful as an input to the sample verb.
Closes #79.
=> Add frac() helper function.

docs/api/verbs.md, src/table/table.js, src/table/transformable.js, src/verbs/expr/slice.js, src/verbs/filter.js, test/verbs/slice-test.js
* Add `slice()` verb to extract contiguous rows from table groups.
Closes #78.
=> Add slice verb.

src/table/table.js
This makes the Table interface a bit more like the native Map and Set, which will similarly support a size getter.
=> Add Table.size getter.

docs/api/verbs.md
Also, seems like this example is a leftover:
aq.table({ keyA: [1, 2], keyB: [3, 4], valueA: [5, 6], valueB: [7, 8 ]})
delete it...
=> Adding syntax highlighting for pivot examples

src/verbs/dedupe.js, test/verbs/dedupe-test.js
- Fix `dedupe()` to produce ungrouped tables.
=> Dedupe output should not be grouped.

docs/api/op.md, src/engine/pivot.js, src/op/aggregate-functions.js, src/op/functions/object.js, src/op/op-api.js, src/util/is-map-or-set.js, src/util/is-set.js, src/verbs/impute.js, test/verbs/derive-test.js, test/verbs/rollup-test.js, test/verbs/unroll-test.js
- (_Breaking_) Rename `op.values` aggregation function to `op.array_agg`.
- (_Breaking_) Rename `op.unique` aggregation function to `op.array_agg_distinct`.
- Add support for Map and Set instances to `op.has()`, `op.keys()`, and `op.values()`.
- Add `op.entries()` function, with support for Object, Map, and Set instances.
This PR is an alternative to #104, but requires a major version bump.
=> Resolve op.values collision by adding array_agg.

src/expression/codegen.js, test/expression/parse-test.js
- Fix table expression code generation for computed object keys (`{['a'+'b']: 'c'}`)
=> Fix codegen for computed object keys.

docs/api/table.md, src/table/column-table.js, src/table/table.js
- Update `table.get(columnName, row)` to default to row index `0` when `row` is unspecified.
=> Add default row index for table.get.

docs/api/table.md, src/table/column-table.js, src/table/index.js, src/table/table.js, src/util/row-object-builder.js, test/table/column-table-test.js
- Add columns option for `table.objects` and `table.print` output.
- Fix `aq.table()` bug with `Map` inputs
=> Add columns option for objects/print output.

src/table/column-table.js, test/table/column-table-test.js
This PR is in favor of #117 given the latest comment there. Added tests and grouped output.
As for the key name itself, for what it's worth I had originally considered `as`, but figured it was a little too vague. Similarly, I thought `groups` implied the columns which are being used for groupings.
=> Grouped Output

docs/api/verbs.md, src/engine/sample.js, src/table/transformable.js, src/util/shuffle.js, test/query/query-test.js
- Add `shuffle` option (default `true`) for the `sample()` verb.
Closes #127.
=> Add shuffle option for sample.

docs/api/op.md, src/engine/reduce/util.js, test/verbs/derive-test.js, test/verbs/rollup-test.js
- Update aggregate calculations to be sensitive to `orderby()` criteria.
Close #130.
=> Make aggregates order sensitive.

src/engine/join-filter.js, src/engine/join.js, src/engine/join/lookup.js, src/engine/lookup.js, src/verbs/join-filter.js, src/verbs/join.js, src/verbs/lookup.js, src/verbs/util/join-keys.js, test/verbs/join-filter-test.js
- Add hash-join support to optimize `semijoin()` and `antijoin()`.
- Refactor join utilities.
Close #136.
=> Optimize semijoin and antijoin performance.

docs/api/index.md, docs/api/op.md, src/helpers/bin.js, src/op/aggregate-functions.js, src/op/op-api.js, src/util/bins.js, test/verbs/rollup-test.js
Updates bin determination functions to additionally support an explicit step size.
* Add `step` option to `aq.bin` helper function.
* Add `step` argument to `op.bins` aggregate function.
Close #145.
=> Add bins step option.

docs/api/verbs.md
Tiny error in the comments of the third example under [pivot](https://uwdata.github.io/arquero/api/verbs#pivot).
=> Fix pivot example

docs/api/table.md, src/table/column-table.js, src/table/table.js, test/table/column-table-test.js
- Add table `values()` method to return an iterator over column values, respecting filter and orderby criteria.
- Add table `array()` method to return a column value array, respecting filter and orderby criteria.
- Deprecate table `columnArray()` method in favor of table `array()` method.
=> Add column value extraction methods.

README.md, docs/index.md, package.json, test/arrow/profiler-test.js, yarn.lock
- Revert Apache Arrow to v3.0.0 until build errors caused by v4.0.0 are resolved.
Close #166.
=> Revert Apache Arrow to v3.0.0.

docs/api/table.md, src/format/to-csv.js, src/format/to-html.js, src/format/util.js, test/format/to-html-test.js
- Add default 100 row limit to `toHTML()` and `toMarkdown()`.
- Update to `toHTML()` to align column header similarly to the column body.
Close #175.
Close #176.
=> Improve output format methods.

src/engine/rollup.js, src/expression/parse-escape.js, src/expression/parse-expression.js, src/op/op-api.js, src/table/transformable.js, src/util/to-array.js, src/util/to-function.js, src/verbs/impute.js, test/helpers/escape-test.js, test/verbs/impute-test.js
* Add support for array literals and escaped values in expression parsing.
* Fix `rollup()` output early exit condition to support literal expressions without aggregate operations.
* Improve TypeScript types. (#182)
* Update impute verb tests.
=> Update TypeScript types, expression literals.

src/helpers/selection.js
- Fix selection helper return types.
Close #203.
=> Fix selection helper return types.

src/table/table.js
When using `print()`, the default value is 10. Users can override this value by setting `limit` in the options object or by providing a numeric value. Unfortunately, if a numeric value was set, the default of 10 was used instead of the provided value.
=> Fix setting limit in print()

src/verbs/helpers/agg.js
This mismatching in case causes typescript to throw an error when compiling/linting Arquero as a dependency.
=> Fix mismatched imports due to casing

src/engine/window/window.js, src/expression/parse.js, test/verbs/derive-test.js
- Fix operator parsing lookup key to include rolling window frame information.
Close #232.
=> Fix use of multiple rolling window frames in the same derive.

src/engine/pivot.js, test/verbs/pivot-test.js
Update pivot verb implementation to make count aggregates perform per-key counts, not global counts.
Fixes #273.
=> Make pivot count respect pivot keys.

src/expression/parse-expression.js, test/expression/params-test.js
- Walk AST subtree to update nodes prior to member property compilation.
Fix #323
=> Fix parameter property compilation.

docs/api/op.md
Hi, the parameter `firstday` in `op.week()` & `op.utcweek()` is not documented even though someone was so kind to implement it.    
I hope that I adjusted the document correctly.
=> Document firstday parameter of op.week() & op.utcweek()

src/format/to-arrow.js, src/table/column-table.js, test/format/to-arrow-test.js
When serializing to IPC format using 
```javascript
table.toArrowBuffer()
``` 
There is no way to specify if the serialization should be in IPC "stream" or "file" format.
The call to tableToIPC here:
https://github.com/uwdata/arquero/blob/074e1efdb6b8df2ca125db0c36020a8feb1d2d66/src/format/to-arrow.js#L6-L8
does not allow any passing of the second option defined in apache-arrow 
https://github.com/apache/arrow/blob/5611f2bd0d6136b005d137a84b50709fc5c813bb/js/src/ipc/serialization.ts#L61-L65
This PR adds a {format} option to the options parameter of toArrowBuffer to allow specification of the IPC format
=> Adds the option for toArrowIPC to write to stream or file formats

src/util/is-iso-date-string.js, test/format/from-csv-test.js, test/format/from-json-test.js
This commit adds a check and tests for invalid dates which still might pass a regex test. I found this is common with government datasets which include years in the format: "2017-18". Technically it still passes the YYYY-MM check, but should not be treated as a date.
```js
const t = aq.fromCSV("year\n2019-20\n2021-22")
t.get('year', 0) // Invalid Date
```
=> iso-date-string: add check for invalid dates

src/op/window-functions.js, src/query/query.js, src/query/verb.js, src/table/column-table.js, src/table/table.js, src/table/transformable.js
Building with `npm run build` resulted in broken Typescript types in several files.
This PR fixes the JSDoc used in `src/` so that the built module has no Typescript errors.
Fixes #332
=> Fixed errors in type documentation

docs/api/index.md, docs/api/table.md, src/format/to-csv.js, src/format/to-html.js, src/format/to-markdown.js, src/format/util.js, test/format/to-csv-test.js
- Add `toCSV` header option.
- Update `toCSV` to include a trailing newline.
- Update tests and docs.
Close #369.
=> Add header option to toCSV method.

src/table/types.ts
- Tighten table expression type signature. Row objects and params will never be undefined.
Fix issue raised in #373.
=> Tighten table expression type signature.

docs/api/verbs.md
Tiny fix - link to section in table of contents of Verbs page was wrong
=> Fix wrong ToC link in verbs.md

docs/api/extensibility.md, docs/api/index.md, docs/api/table.md, docs/api/verbs.md
- Update docs to track major version updates.
Fixes #376.
=> Update docs to track major version updates.

docs/api/verbs.md, src/table/ColumnTable.js, src/verbs/lookup.js, test/verbs/lookup-test.js
- Update `lookup` verb so that lookup keys and values are optional. The default keys are now all columns with matching names. The default values are all columns in the secondary table whose names do no match any columns in the primary table.
- Update `lookup` verb types and documentation.
Close #379.
=> Make lookup verb keys and values optional.

src/format/stream/delimited-text-stream.js, test/format/from-csv-test.js
=> Fix CSV quote handling.
