docs/api/op.md

https://uwdata.github.io/arquero/api/op#substring

Update op.md: the 2nd substring should be split

---

docs/api/op.md

wrong name in first_value function

fix: wrong function name for last_value

---

.eslintrc.js
src/op/aggregate-functions.js
src/op/op.js
src/util/is-bigint.js
src/util/is-date.js
src/util/is-regexp.js
src/util/max.js
src/util/min.js
src/util/object-to-string.js
src/util/product.js
src/util/quantile.js
src/util/to-numeric.js
src/util/to-string.js
test/verbs/derive-test.js
test/verbs/rollup-test.js

- Add `BigInt` support, including for `sum`, `product`, `median`, and `quantile` aggregation functions.
- Fix `product` aggregation streaming (windowed) behavior.
- Fix `unique` aggregation streaming (windowed) behavior.

Add BigInt support.

---

docs/api/index.md
src/query/to-ast.js
src/query/util.js
src/util/escape-regexp.js
src/verbs/expr/selection.js
src/verbs/index.js
test/query/verb-test.js
test/query/verb-to-ast-test.js
test/verbs/select-test.js

- Add `matches`, `startswith`, `endswith` selection helpers.
Close #34

Add matches, startswith, endswith selection helpers.

---

docs/api/op.md
src/op/functions/index.js
src/op/functions/recode.js
test/verbs/derive-test.js

* Add `op.recode()` function to map input values to recoded values.
Close #29.

Add recode function.

---

docs/api/op.md
src/op/functions/string.js

- Fix `op.match` to use the proper string match method.

Use proper string match method.

---

docs/api/op.md
src/op/op-api.js
src/op/window-functions.js
test/verbs/derive-test.js

- Add `fill_down` and `fill_up` window functions.

Add fill_down, fill_up window functions.

---

docs/api/index.md
src/format/from-arrow.js
src/verbs/expr/selection.js
test/format/arrow-test.js

- Add support for pre-filtered Apache Arrow tables.
- Add flexible column selection for Apache Arrow import.
Close #51.

Extend Apache Arrow import support.

---

src/index.js
src/table/column-table.js
src/table/column.js
src/table/table.js

* Add column factory mechanism, expose as `internal.columnFactory()` getter/setter.

Add configurable column factory.

---

src/engine/concat.js
src/engine/join.js
src/engine/lookup.js
src/engine/spread.js
src/op/aggregate-functions.js
src/op/functions/array.js
src/op/window-functions.js
src/util/max.js
src/util/min.js
src/util/null.js
src/util/quantile.js
src/util/value-list.js
src/verbs/join.js

* Consolidate default null / missing value.

Consolidate default NULL (missing) value.

---

docs/api/table.md
src/table/column-table.js
src/table/table.js
test/table/column-table-test.js

- Add table `columnArray` method.

Add table columnArray method.

---

docs/api/op.md
src/engine/reduce/field-reducer.js
src/op/aggregate-functions.js
src/op/op-api.js
test/verbs/rollup-test.js

- Add `op.object.agg` aggregate function.

Add object_agg aggregate.

---

docs/api/op.md
src/op/functions/array.js
test/op/array-test.js

- Add `op.compact` function for filtering invalid values from an array.

Add op.compact function.

---

src/engine/reduce/field-reducer.js
src/engine/window/window.js
src/op/aggregate-functions.js
src/util/value-list.js

- Update aggregate value collector to avoid unnecessary array copies.

Optimize aggregate value collector.

---

docs/api/op.md
src/op/functions/index.js
src/op/functions/json.js
test/op/json-test.js

- Add `op.parse_json` and `op.to_json` functions.

Add JSON functions.

---

src/op/aggregate-functions.js
src/op/op-api.js
test/verbs/rollup-test.js

- Add `map_agg` and `entries_agg` aggregate functions.

Add map_agg and entries_agg.

---

src/engine/reduce/util.js
test/verbs/pivot-test.js

Fix ordered aggregate scan.

---

src/op/functions/array.js
src/op/functions/object.js
src/op/functions/string.js
test/op/array-test.js
test/op/object-test.js
test/op/string-test.js

- Fix `op` functions to properly handle null-valued inputs.
- Add test cases for many op functions.
Close #144.

Fix op function null handling.

---

docs/api/verbs.md
src/query/verb.js
src/table/transformable.js
src/verbs/index.js
src/verbs/rename.js
test/query/query-test.js
test/query/verb-test.js
test/query/verb-to-ast-test.js
test/verbs/rename-test.js

- Add `rename()` verb.
Close #150.

Add rename verb.

---

src/expression/parse.js

- Add more detailed messages for variable and function lookup errors.
- Fix error message for when no window functions are allowed.
- Refactor expression parser error message handler.

Improve table expression parser error messages.

---

docs/api/table.md
src/table/column-table.js
src/table/table.js
test/table/column-table-test.js

- Add table `object()` method to extract individual row objects.

Add table object method.

---

docs/api/index.md
src/format/from-csv.js
src/util/parse-values.js
test/format/from-csv-test.js

- Add `decimal` separator option to `fromCSV()`.
Close #160

Add decimal option to fromCSV.

---

src/table/column-table.js
src/table/index.js
test/table/column-table-test.js

- Add object/map input support for table `assign()` method.

Add object/map input support for table assign.

---

docs/api/table.md
src/table/column-table.js
test/table/column-table-test.js

- Add table `transform()` method to allow lightweight application of custom transformations.

Add table transform() method.

---

docs/api/index.md
src/index.js
src/verbs/helpers/agg.js
test/verbs/agg-test.js

Add agg() helper method.

---

src/format/from-text-rows.js
test/format/from-csv-test.js

- Fix explicit parser lookup with autoType false.
Close #184.

Fix explicit parser lookup with autoType false.

---

src/arrow/arrow-column.js
src/arrow/encode/index.js
src/format/from-arrow.js
src/format/from-csv.js
src/format/from-fixed.js
src/format/from-json.js
src/format/load-file.js
src/format/load-url.js
src/format/to-csv.js
src/format/to-html.js
src/format/to-json.js
src/format/to-markdown.js
src/format/util.js
src/op/op-api.js
src/table/table.js
src/table/transformable.js
src/verbs/helpers/agg.js

- Improve JSDoc comments and typings.
Close #125.

Improve JSDoc comments and typings.

---

docs/api/index.md

loadFixed method mentioned 'load a CSV' file. Small typo fix.

Fixed typo in documentation

---

src/table/table.js
test/table/column-table-test.js

- Fix early termination for filtered table scans.
Close #235.

Fix early termination for filtered table scans.

---

src/table/table.js

Table print should return the table instance.

---

package-lock.json
package.json
test/format/to-arrow-test.js

fixes #345
It looks like the difference in the IPC in the tests is due to vectors being nullable now: https://github.com/apache/arrow/pull/39436, https://github.com/apache/arrow/pull/39253, https://github.com/apache/arrow/pull/39254.

feat: update to arrow 15

---

package-lock.json
package.json
src/format/stream/collect.js
src/format/stream/line-filter-stream.js
src/format/stream/parse-json-rows.js
src/format/stream/parse-text-rows.js
src/format/stream/stream-iterator.js

- Add internal stream iterator method to sidestep Safari limitations.
Fixes #389.

Add internal stream iterator method.

---

src/verbs/reduce/util.js
test/verbs/rollup-test.js
test/verbs/slice-test.js

- Fix filtered and ordered aggregate row count.
Close #393.

Fix filtered aggregate row count.

---

src/format/stream/delimited-text-stream.js
test/format/data/text-stream.js
test/format/from-csv-test.js

- Fix CSV cross-chunk quote handling.
Close #395.

Fix CSV cross-chunk quote handling.
